### ISSUE TITLE
Automate submission phase of pipeline

### ISSUE THREAD

**Issue by wnkhan** [kids-first/c2m2-submission-process#16]
Currently, the submission phase is run by executing a couple of cli commands utilizing the cfde-submit tool, to both initiate the submission and check status.

Certainly, this could be automated, however there is an authentication piece that may make the automation of this phase non-trivial, especially for an unfamiliar implementer.

**Comment by cnemarich** [comment]
Can't do this anymore since CFDE has deprecated the submit tool
