### ISSUE TITLE
cfde-submit tool dependency conflicts

### ISSUE THREAD

**Issue by wnkhan** [kids-first/c2m2-submission-process#18]
### cfde-submit Tool Dependency Conflicts

- Dependency Conflicts
1. typing-extensions
2. PyJWT

There are dependency issues between the fhir-pyrate and submit tool, however the submit tool is separate from the etl process and a separate virtual environment can be used for the submit tool.

The proposal would be to create a separate project partition with a unique virtual environment for submitting.

**Comment by cnemarich** [comment]
No longer relevant since cfde-submit tool has been deprecated
